main_settings:
  colorizer: LEGACY
  exact_equality: false
  commands:
    - '/op'
    - '/whitelist'

gui_settings:
  menu_title: '&4Подтвердите команду!'
  size: 26
  items:
    confirm_item:
      display_name: '&aПодтвердить'
      lore: []
      material: LIME_STAINED_GLASS_PANE
      slots:
        - 0-3
        - 9-14
        - 18-22
      action: CONFIRM
    cancel_item:
      display_name: '&cОтклонить'
      lore: []
      material: RED_STAINED_GLASS_PANE
      slots:
        - 4-8
        - 14-17
        - 23-26
      action: CANCEL
    filter_item:
      display_name: '&r'
      lore: []
      material: BLACK_STAINED_GLASS_PANE
      slots:
        - 4
        - 13
        - 22
      action: NAN

messages:
  help: "&aИспользование: /ccgui <reload|add|remove|help>"
  no_perms: "&cУ вас нет прав!"
  reloaded: "&aКонфигурация успешно перезагружена."
  add_command: "&aКоманда &6%command% &aдобавлена."
  remove_command: "&cКоманда &6%command% &cудалена."
  add_or_remove_help: "&cУкажите команду!"
  cancelled: "&cВы отменили выполнение команды."

